services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    working_dir: /app
    volumes:
      - ./:/app

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
